export enum PurchaseType {
  shirt = 'shirt',
  tshirt = 'tshirt',
  jeans = 'jeans',
  sweater = 'sweater',
  coat = 'coat',
  dress = 'dress',
  shoes = 'shoes',
  smartphone = 'smartphone',
  tablet = 'tablet',
  computer = 'computer',
  laptop = 'laptop',
  fossilFuelCar = 'fossil fuel car',
  eletricCar = 'eletric car',
}
