export enum FoodType {
  coffee = 'coffee',
  chocolate = 'chocolate',
  redMeat = 'redMeat',
  whiteMeat = 'whiteMeat',
  fish = 'fish',
  lamb = 'lamb',
  beef = 'beef',
  cheese = 'cheese',
  pork = 'pork',
  turkey = 'turkey',
  chicken = 'chicken',
  tuna = 'tuna',
  eggs = 'eggs',
  potatoes = 'potatoes',
  rice = 'rice',
  nuts = 'nuts',
  beans = 'beans',
  tofu = 'tofu',
  vegetables = 'vegetables',
  milk = 'milk',
  fruit = 'fruit',
  lentils = 'lentils',
}
