export enum TransportType {
  plane = 'plane',
  bus = 'bus',
  boat = 'boat',
  car = 'car',
  fossilFueledCar = 'fossilFueledCar',
  electricVehicle = 'electricVehicle',
  hybridCar = 'hybridCar',
  carSharing = 'carSharing',
  motorbike = 'motorbike',
  shortDistanceBus = 'shortDistanceBus',
  longDistanceBus = 'longDistanceBus',
  train = 'train',
  shortHaulFlight = 'shortHaulFlight',
  mediumHaulFlight = 'mediumHaulFlight',
  longHaulFlight = 'longHaulFlight',
}
